// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPCS.Data;

#nullable disable

namespace SPCS.Data.Migrations
{
    [DbContext(typeof(SPCSContext))]
    [Migration("20260118121545_ConfigureEntityRelationshipsAndDecimalPrecision")]
    partial class ConfigureEntityRelationshipsAndDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPCS.Common.Models.SPCSConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("SPCS.Concurrency.Models.ConcurrencyCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConcurrencyMetric")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("NeedCoverage")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.ToTable("ConcurrencyCalculations");
                });

            modelBuilder.Entity("SPCS.Concurrency.Models.PowerTimestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcurrencyCalculationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.HasIndex("ConcurrencyCalculationId");

                    b.HasIndex("FileId");

                    b.ToTable("PowerTimestamp");
                });

            modelBuilder.Entity("SPCS.Files.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SPCS.Files.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SPCS.Files.Models.ParsedTimestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumptionValue")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductionValue")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("ParsedTimestamps");
                });

            modelBuilder.Entity("SPCS.Concurrency.Models.PowerTimestamp", b =>
                {
                    b.HasOne("SPCS.Concurrency.Models.ConcurrencyCalculation", "ConcurrencyCalculation")
                        .WithMany("PowerTimestamps")
                        .HasForeignKey("ConcurrencyCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPCS.Files.Models.File", null)
                        .WithMany("Timestamps")
                        .HasForeignKey("FileId");

                    b.Navigation("ConcurrencyCalculation");
                });

            modelBuilder.Entity("SPCS.Files.Models.File", b =>
                {
                    b.HasOne("SPCS.Files.Models.Application", "Application")
                        .WithMany("Files")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SPCS.Files.Models.ParsedTimestamp", b =>
                {
                    b.HasOne("SPCS.Files.Models.File", "File")
                        .WithMany("ParsedTimestamps")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("SPCS.Concurrency.Models.ConcurrencyCalculation", b =>
                {
                    b.Navigation("PowerTimestamps");
                });

            modelBuilder.Entity("SPCS.Files.Models.Application", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SPCS.Files.Models.File", b =>
                {
                    b.Navigation("ParsedTimestamps");

                    b.Navigation("Timestamps");
                });
#pragma warning restore 612, 618
        }
    }
}
